# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "kmaster" do |node|
  

    node.vm.box               = "generic/debian10"
    node.vm.box_check_update  = false
    node.vm.hostname          = "kmaster.lab.local"

    node.vm.network "private_network", ip: "172.16.16.100"
    node.vm.network "forwarded_port", id: "ssh",  guest: 22, host: 2277

    node.vm.provider :virtualbox do |v|
      v.name    = "kmaster"
      v.memory  = 4096
      v.cpus    =  2
    end

  
    node.vm.provider :libvirt do |v|
      v.memory  = 4096
      v.nested  = true
      v.cpus    = 2
    end
  
    node.vm.provision "shell", path: "bootstrap_kmaster.sh"
  
  end


  # Kubernetes Worker Nodes
  NodeCount = 2

  (1..NodeCount).each do |i|

    config.vm.define "kworker#{i}" do |node|

      node.vm.box               = "generic/debian10"
      node.vm.box_check_update  = false
      node.vm.hostname          = "kworker#{i}.lab.local"

      node.vm.network "private_network", ip: "172.16.16.10#{i}"
      node.vm.network "forwarded_port", id: "ssh",  guest: 22, host: "228#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "kworker#{i}"
        v.memory  = 2048
        v.cpus    = 2
      end

      node.vm.provider :libvirt do |v|
        v.memory  = 2048
        v.nested  = true
        v.cpus    = 2
      end

      node.vm.provision "shell", path: "bootstrap_kworker.sh"

    end

  end

end